In [3]:
import numpy as np

#Se crea un arreglo
arr = np.array([1, 2, 3])

#Arreglos especiales
a = [1, 2, 3]
b = [1, 1, 1]
c = np.array([1, 1, 1])

(3,)
1


In [7]:
#Entrega cantidad de (dimensiones, elementos) en ellas.
print(arr.shape)

#Número de dimensiones de un arreglo
print(arr.ndim)

#Cantidad de entradas que tiene el arreglo
print(arr.size)

(3,)
1
3


In [16]:
q = np.array([[1, 2], [3, 4], [1, 3], [2, 4]])
r = np.array([1, 2, 3])

q.shape #(4, 2)

(4, 2)

In [17]:
q.ndim #2

2

In [18]:
q.size #6

8

In [19]:
r.ndim #1

1

In [21]:
#Crear un arreglo de ceros
#4 filas, 10 columnas
t = np.zeros((4, 10))

In [24]:
#Crear un arreglo de unos
a = np.ones((2, 10))

In [27]:
#Crear un arreglo lleno de una constante
b = np.full((3, 5), 3.14)

In [29]:
#Arreglo vacío
c = np.empty(11)

In [31]:
#Arreglo con números aleatorios entre el 0 y 9
# (valor ini, valor final+1, tamaño)
d = np.random.randint(0, 10, 15)

In [34]:
#Arreglo con números desde el 5 al 30 con saltos de a 3
#El último número no lo considera
e = np.arange(5, 32, 3)

In [37]:
#Arreglo equiespaciado de 0 a 1 con 11 puntos
#Genera un arreglo con 11 elementos equiespaciados.
f = np.linspace(0, 1, 11)

In [42]:
g = np.array([1, 2, 3])
h = np.array([1, -1, 2])
print(g+h)
print(g-h)
print(g*h)
print(g/h)

[2 1 5]
[0 3 1]
[ 1 -2  6]
[ 1.  -2.   1.5]


In [43]:
print(np.exp(g))
print(np.sqrt(g))
print(np.sin(h))
print(np.log(g))

[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[ 0.84147098 -0.84147098  0.90929743]
[0.         0.69314718 1.09861229]


In [47]:
arr = np.array([1, 2, 4, 6, 7, 8, 9, 98, 76, 98, 65])
arr[-2]
arr[9]
arr[0]
np.size(arr)

11

In [48]:
for i in np.arange(np.size(arr)):
    print(arr[-1-i])

65
98
76
98
9
8
7
6
4
2
1


In [49]:
w = ['hola', 'mundo', 'chao']
#Número de items en una lista
len(w)

3

In [50]:
len(arr)

11

In [51]:
for i in arr:
    print(i)

1
2
4
6
7
8
9
98
76
98
65


In [52]:
#Encontrar el peak de un arreglo
# a[k-1] <= a[k] y a[k+1] <= a[k]

a = np.array([5, 2, 3, 2, 3, 2, 3, 4])

def BuscarPeak(a):
    for i in np.arange(1, len(a) - 1):
        if a[i] >= a[i-1] and a[i] >= a[i+1]:
            print("La posición", i, "es un peak")
            
BuscarPeak(a)

La posición 2 es un peak
La posición 4 es un peak


In [54]:
b = np.random.randint(0, 10, 20)
print(b)
BuscarPeak(b)

[1 1 8 3 1 9 2 7 4 2 4 9 0 1 4 7 9 7 1 6]
La posición 2 es un peak
La posición 5 es un peak
La posición 7 es un peak
La posición 11 es un peak
La posición 16 es un peak


In [55]:
#Matrices
#Se crea una matriz de 2x3

A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [56]:
print(A.shape)
print(A.ndim)
print(A.size)
print(len(A))

(2, 3)
2
6
2


In [58]:
#Segunda fila, tercer elemento
#(fila-1, columna-1)
print(A[1, 2])

5


In [59]:
#Primera fila, último elemento
print(A[0, -1])

3


In [60]:
#Primera fila
print(A[0])

[1 2 3]


In [61]:
#Matrices como arreglos de arreglos
for x in A:
    print(x)

[1 2 3]
[3 4 5]


In [62]:
#Se puede recorrer de la siguiente manera:
for x in A:
    for y in x:
        print(y)

1
2
3
3
4
5


In [63]:
#Recorre columna por columna
for j in range(3):
    for i in range(2):
        print(A[i, j])

1
3
2
4
3
5


In [64]:
#Recorre fila por fila
for i in range(2):
    for j in range(3):
        print(A[i, j])

1
2
3
3
4
5


In [65]:
for i in range(2):
    print(A[i, 1])


2
4
