In [1]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
%matplotlib inline

#a) Definir un arreglo de dos filas y dos columnas

A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [7]:
#b) Calcular la suma de los elementos de su arreglo
suma = 0
contador = 0
menores_que = 0
for i in range(2):
    for j in range(2):
        if A[i, j] < 6:
            menores_que += 1
        contador += 1
        suma = suma + A[i, j]
print(suma)

10


In [6]:
#c) Calcular el promedio de los elementos de su arreglo
print(contador)
promedio = suma/contador
print(promedio)

4
2.5


In [8]:
#d) Determinar la cantidad de elementos de su arreglo que son menores que 6.
print(menores_que)

4


In [10]:
#e) Determinar el valor y posición del elemento más grande de su arreglo.
a = -1000
num_f = 0
num_c = 0

for i in range(2):
    for j in range(2):
        if a < A[i, j]:
            a = A[i, j]
            num_f = i+1
            num_c = j+1
            
print(a)
print(num_f, num_c)

4
2 2


In [12]:
#f) Determine el valor y posición del elemento más pequeño de su arreglo.
b = 100000
num_f = 0
num_c = 0

for i in range(2):
    for j in range(2):
        if b > A[i, j]:
            b = A[i, j]
            num_f = i + 1
            num_c = j + 1
print(b)
print(num_f, num_c)

1
1 1


In [13]:
#g) Determinar el elemento que más se repite en su arreglo
print(A)


[[1 2]
 [3 4]]


In [33]:
#Matrices aleatorias
np.random.seed(1)
B = np.random.randint(100, size=(5, 5))
B

array([[37, 12, 72,  9, 75],
       [ 5, 79, 64, 16,  1],
       [76, 71,  6, 25, 50],
       [20, 18, 84, 11, 28],
       [29, 14, 50, 68, 87]])

In [ ]:
#h

In [ ]:
#i

In [35]:
#j

In [36]:
#k

In [ ]:
#l

In [ ]:
#m

In [ ]:
#n

In [37]:
#o

In [ ]:
#p) El más importante